### ISSUE TITLE
UnboundLocalError: local variable 'LANG_KEYS' referenced before assignment

### ISSUE THREAD

**Issue by hiasel** [rogermolas/CSVLocalizer#13]
I tried to convert the provided `sample.csv` (https://github.com/rogermolas/csv-localizer/blob/master/sample.csv) to ios localized strings using: `csv-localizer -p ios -i sample.csv -o ios-output`.
However I receive the following error and nothing is generated.
Any help would be much appreciated :)

```
Start Localizing ....


------------------------------------
Generated output directory: ios-output
Traceback (most recent call last):
  File "/Users/myuser/homebrew/bin/csv-localizer", line 278, in <module>
    main(args, loglevel)
  File "/Users/myuser/homebrew/bin/csv-localizer", line 70, in main
    generate_keys(IN_PATH, OUTPUT_DIR, PLATFORM, DELIMITER)
  File "/Users/myuser/homebrew/bin/csv-localizer", line 121, in generate_keys
    start_localize_ios(source_path, allwrites, LANG_KEYS, delimiter)
UnboundLocalError: local variable 'LANG_KEYS' referenced before assignment
```

**Comment by hiasel** [comment]
Duplicate of #8

Nevermind, this is a duplicate issue. It works fine using the commands you described in the issue.
